### ISSUE TITLE
Default date cached on app startup

### ISSUE THREAD

**Issue by staticlibs** [dansalias/aws_s3_presign#9]
The date of app startup is used [as a default](https://github.com/dansalias/aws_s3_presign/blob/34368e1cbf2baa866b70520710491388ef4cfc5d/mod.ts#L10) for `X-Amz-Date` parameter, this seems to be not intentional as it is [supposed to be a request timestamp](https://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-query-string-auth.html#query-string-auth-v4-signing-example).

**Comment by martpet** [comment]
I can confirm, my app was running without restart for a long time when I started getting `Request has expired`.

**Comment by dansalias** [comment]
Fixed in 2.2.1. The current date is used at `getSignedUrl`() call time.
